In [4]:
from pathlib import Path
import pandas as pd

DATADIR = '/mnt/d/WSI/CAMELYON16'
assert Path(DATADIR).exists()

df = pd.read_csv(f'{DATADIR}/csv/labeled_camelyon16.csv')

In [13]:
'''
LABELS
0 -> normal
1 -> abnormal
2 -> normal patch in abnormal slide
3 -> patches in the border of the annotation
'''

positive_df = df.query("slide_label == 1")
pd.pivot_table(positive_df, index=['subset', 'label'], values=['img_path'], aggfunc='count')

              img_path
subset label
test   1         54129
       2        210564
       3          4550
train  1         64924
       2        600610
       3         10256

In [11]:
df

,subset,slide,img_path,img_size_kb,label,slide_label
0,train,normal_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,25.131836,0,0
1,train,normal_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,22.099609,0,0
2,train,normal_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,22.414062,0,0
3,train,normal_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,22.772461,0,0
4,train,normal_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,18.392578,0,0
...,...,...,...,...,...,...
2271992,test,test_130,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,22.602539,0,0
2271993,test,test_130,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,23.920898,0,0
2271994,test,test_130,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,20.109375,0,0
2271995,test,test_130,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,16.099609,0,0
2271996,test,test_130,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,16.218750,0,0

In [22]:
# DIVIDING TRAIN/VAL BY SLIDES
import random

train_df = df.query("subset=='train'")
new_df = df.query("subset=='test'")

train_perc = .8

for label in [0, 1]:
    random.seed(2024)
    subdf = train_df.query(f"slide_label=={label}")
    slide_names = subdf['slide'].unique()
    n_train = int(len(slide_names) * train_perc)
    selected_slides = random.sample(list(slide_names), n_train)

    train_subdf = subdf.query(f"slide in {selected_slides}")
    val_subdf = subdf.query(f"slide not in {selected_slides}")
    val_subdf['subset'] = 'val'

    new_df = pd.concat([new_df, train_subdf, val_subdf], axis=0)

/tmp/ipykernel_948594/2092006442.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_subdf['subset'] = 'val'
/tmp/ipykernel_948594/2092006442.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_subdf['subset'] = 'val'

In [30]:
import numpy as np

pd.pivot_table(new_df, index=['subset', 'slide_label'], values=['slide'], aggfunc=lambda x: np.unique(x).shape[0])

                    slide
subset slide_label
test   0               88
       1               41
train  0              135
       1               80
val    0               34
       1               21

In [35]:
train_slides = new_df.query("subset=='train'")['slide'].unique()
val_slides = new_df.query("subset=='val'")['slide'].unique()

set(train_slides) & set(val_slides)

set()

In [36]:
new_df.to_csv("csv/camelyon16_data.csv", index=False)

In [37]:
'''
LABELS
0 -> normal
1 -> abnormal
2 -> normal patch in abnormal slide
3 -> patches in the border of the annotation
'''

,subset,slide,img_path,img_size_kb,label,slide_label
1542569,test,test_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,17.959961,2,1
1542570,test,test_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,17.202148,2,1
1542571,test,test_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,17.750977,2,1
1542572,test,test_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,16.882812,2,1
1542573,test,test_001,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,17.947266,2,1
...,...,...,...,...,...,...
1542564,val,tumor_111,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,20.204102,2,1
1542565,val,tumor_111,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,20.218750,2,1
1542566,val,tumor_111,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,21.076172,2,1
1542567,val,tumor_111,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,19.930664,2,1
1542568,val,tumor_111,/mnt/d/WSI/CAMELYON16/camelyon16_patch_256_20x...,17.507812,2,1

In [38]:
import torch

a = torch.load("models/supervised_resnet18.pth")

In [40]:
a['state_dict']

OrderedDict([('backbone.conv1.weight',
              tensor([[[[ 2.5167e-02,  5.4288e-02, -3.5951e-02,  ...,  7.7984e-02,
                          1.3417e-02, -9.3965e-03],
                        [-2.0568e-02,  5.3696e-02, -5.8493e-02,  ...,  7.4035e-02,
                         -4.0631e-02,  1.9521e-03],
                        [-2.4114e-02,  1.5787e-01, -7.6331e-02,  ...,  8.4116e-02,
                         -4.4171e-02,  3.5973e-02],
                        ...,
                        [ 4.5541e-02,  1.6133e-01, -3.6068e-01,  ...,  7.0760e-02,
                         -1.7587e-02,  1.9499e-02],
                        [ 6.6744e-02,  1.4916e-02, -2.2822e-01,  ...,  6.9160e-03,
                          3.3283e-02,  1.1854e-02],
                        [ 2.8907e-02, -2.5122e-03, -1.1278e-01,  ..., -2.7575e-02,
                          3.6057e-02, -2.1331e-02]],

                       [[-4.4951e-02,  1.0936e-01,  5.3916e-02,  ..., -7.6071e-03,
                          2.5346e-02, -1.4528e-02],
                        [-3.0909e-02,  1.9437e-01,  6.2212e-03,  ...,  2.9799e-02,
                         -1.3654e-02, -8.4365e-03],
                        [ 3.6697e-02,  3.3916e-01, -1.2686e-01,  ...,  1.6004e-01,
                          9.7770e-03,  4.0172e-02],
                        ...,
                        [ 1.6867e-01,  1.3145e-01, -8.3509e-01,  ...,  2.6160e-01,
                          2.6645e-03,  2.0710e-02],
                        [ 1.2020e-01, -2.2804e-01, -3.9919e-01,  ...,  1.0176e-01,
                          1.2342e-02, -1.8801e-02],
                        [-3.4719e-02, -2.2546e-01, -3.6844e-02,  ..., -9.7656e-03,
                          8.3720e-03, -1.7277e-02]],

                       [[-6.5341e-02,  8.0380e-02,  8.2851e-02,  ..., -6.6652e-02,
                          3.3481e-02,  2.1176e-02],
                        [-8.1288e-02,  1.7482e-01,  3.6718e-02,  ...,  9.5280e-03,
                          5.9589e-02, -7.2498e-03],
                        [-1.9412e-02,  3.4676e-01, -1.7839e-01,  ...,  2.2425e-01,
                          7.4407e-02, -1.9294e-02],
                        ...,
                        [ 2.2001e-01,  6.2151e-02, -8.0332e-01,  ...,  3.4764e-01,
                         -2.9223e-02, -4.0057e-02],
                        [ 1.4109e-01, -3.2602e-01, -3.3061e-01,  ...,  8.6058e-02,
                         -5.0535e-02, -3.7051e-02],
                        [-5.3020e-02, -2.6637e-01,  4.5006e-02,  ..., -2.9728e-02,
                         -4.8281e-02, -1.8597e-02]]],


                      [[[ 2.1727e-02, -1.3596e-01,  1.9787e-02,  ...,  2.9810e-01,
                          5.3515e-02, -1.9305e-01],
                        [-9.0858e-02, -2.9132e-01, -4.2288e-02,  ...,  2.5755e-01,
                         -9.5189e-03, -3.0662e-01],
                        [-9.9876e-02, -3.9144e-01, -2.6744e-02,  ...,  2.6789e-01,
                         -1.3084e-01, -3.8871e-01],
                        ...,
                        [-7.7171e-02, -3.9566e-01,  1.4846e-01,  ...,  2.4108e-01,
                         -2.9077e-01, -2.3211e-01],
                        [-1.6192e-01, -3.0607e-01,  1.6804e-01,  ...,  3.9095e-02,
                         -2.2115e-01, -1.9180e-01],
                        [-1.2393e-01, -1.5794e-01,  2.3472e-01,  ...,  7.3608e-02,
                         -1.1383e-01, -1.6105e-01]],

                       [[-6.9541e-03, -1.6185e-01, -3.9536e-02,  ...,  2.9744e-01,
                          4.5503e-02, -2.3582e-01],
                        [-1.2206e-01, -3.7241e-01, -1.2354e-01,  ...,  2.1007e-01,
                         -9.1941e-02, -4.8121e-01],
                        [-3.2785e-02, -4.3885e-01, -1.9417e-02,  ...,  2.7957e-01,
                         -1.7090e-01, -5.5287e-01],
                        ...,
                        [-3.4776e-02, -4.5051e-01,  1.8748e-01,  ...,  2.5293e-01,
                         -3.6792e-01, -2.7083e-01],
                        [-1.5994e-01, -3.3514e-01,  1.6733e-01,  ..., -3.3240e-02,
                         -3.3014e-01, -2.5089e-01],
                        [-6.6064e-02, -9.8262e-02,  2.4423e-01,  ...,  9.2812e-03,
                         -1.3979e-01, -1.6880e-01]],

                       [[-2.9892e-02, -8.5314e-02,  2.9767e-05,  ...,  9.8279e-02,
                          7.8541e-03, -8.1349e-02],
                        [-1.1134e-01, -1.4130e-01, -6.7603e-02,  ..., -4.2059e-02,
                         -8.6509e-02, -2.0196e-01],
                        [-4.1912e-03, -1.3603e-01, -9.3623e-03,  ...,  1.7625e-02,
                         -6.9367e-02, -1.9949e-01],
                        ...,
                        [ 4.7013e-02, -1.6113e-01,  8.2139e-02,  ...,  5.8114e-02,
                         -1.4739e-01, -5.4395e-02],
                        [-1.4111e-02, -1.2822e-01,  8.1347e-02,  ..., -1.0440e-01,
                         -9.0455e-02, -9.4322e-02],
                        [ 2.2293e-02, -3.3024e-02,  1.0838e-01,  ..., -4.5787e-02,
                         -5.6468e-02, -1.2606e-01]]],


                      [[[-2.1912e-01, -1.4959e-01, -3.6043e-02,  ...,  9.1068e-02,
                         -1.8759e-02, -2.3004e-01],
                        [-9.6204e-02,  3.7785e-02,  1.5019e-01,  ...,  1.2372e-01,
                         -1.0084e-01, -4.4495e-01],
                        [ 6.4084e-02,  3.0128e-01,  3.4920e-01,  ...,  1.5258e-01,
                         -1.7606e-01, -4.2806e-01],
                        ...,
                        [ 2.0215e-01,  4.4310e-01,  3.1055e-01,  ...,  1.2413e-01,
                         -3.1242e-01, -3.6712e-01],
                        [ 1.5901e-01,  3.6039e-01,  3.3964e-01,  ...,  4.4379e-02,
                         -1.9377e-01, -2.6278e-01],
                        [-1.9678e-02,  3.6584e-01,  3.1683e-01,  ...,  8.2058e-02,
                         -7.3837e-03, -9.5508e-02]],

                       [[-4.5297e-02, -8.4495e-03,  3.3860e-02,  ...,  5.9451e-02,
                         -7.4250e-02, -2.5588e-01],
                        [-3.4478e-02,  1.4427e-01,  2.0322e-01,  ...,  5.2296e-02,
                         -6.8148e-02, -4.2483e-01],
                        [ 1.0304e-01,  4.4111e-01,  3.4830e-01,  ...,  1.2796e-01,
                         -1.3681e-01, -4.3185e-01],
                        ...,
                        [ 2.2778e-01,  4.5342e-01,  3.7575e-01,  ...,  6.9499e-02,
                         -3.5212e-01, -4.1585e-01],
                        [ 1.7705e-01,  4.3849e-01,  3.9612e-01,  ...,  8.2571e-03,
                         -1.7661e-01, -2.5224e-01],
                        [-4.8426e-02,  4.8623e-01,  4.9402e-01,  ...,  1.0309e-01,
                          1.5070e-02, -2.9919e-02]],

                       [[ 1.2877e-02,  7.9024e-02,  6.0800e-02,  ..., -1.9347e-02,
                         -1.6191e-02, -2.0632e-01],
                        [ 2.4383e-03,  1.6449e-01,  1.1719e-01,  ...,  2.4588e-02,
                         -8.1642e-03, -2.8975e-01],
                        [ 2.3436e-02,  2.3268e-01,  1.8725e-01,  ...,  3.9046e-02,
                         -5.3411e-02, -2.9979e-01],
                        ...,
                        [ 8.5052e-02,  2.9411e-01,  2.5879e-01,  ..., -3.1206e-02,
                         -1.5114e-01, -2.4206e-01],
                        [ 1.5727e-01,  3.0232e-01,  2.1723e-01,  ..., -4.5146e-02,
                         -5.6232e-02, -7.5947e-02],
                        [ 8.9857e-02,  3.1986e-01,  2.3463e-01,  ..., -4.5769e-03,
                          7.1611e-02,  8.2105e-02]]],


                      ...,


                      [[[-9.5632e-03, -1.3949e-01, -4.0594e-02,  ...,  2.6925e-01,
                          1.5682e-01, -1.4371e-02],
                        [-1.1201e-01, -1.6399e-01,  5.7179e-02,  ...,  2.5151e-01,
                          9.3818e-02, -9.4669e-02],
                        [-5.1816e-02, -4.0559e-02,  1.3795e-01,  ...,  2.5803e-01,
                          3.6741e-02,  2.3392e-02],
                        ...,
                        [ 1.6993e-02,  1.2885e-01,  5.6219e-02,  ..., -3.6719e-02,
                         -1.6394e-02, -7.6822e-02],
                        [-2.2520e-02,  1.0202e-02, -5.5685e-04,  ..., -1.3354e-01,
                         -4.8119e-02, -1.3058e-01],
                        [ 6.2368e-02,  1.4139e-01,  1.4310e-01,  ...,  1.4951e-02,
                         -5.0371e-02, -2.1972e-02]],

                       [[-2.5034e-02, -4.8927e-01, -4.4918e-01,  ...,  1.6984e-01,
                          2.9986e-01,  2.4702e-01],
                        [-3.8119e-01, -7.1290e-01, -4.5453e-01,  ...,  3.1389e-01,
                          3.4853e-01,  9.8019e-02],
                        [-3.8952e-01, -4.8923e-01, -8.5533e-02,  ...,  6.1806e-01,
                          4.7076e-01,  1.3548e-01],
                        ...,
                        [-1.9653e-01, -2.6540e-02,  3.7440e-01,  ...,  5.2539e-01,
                         -1.0032e-02, -1.8084e-01],
                        [-9.1444e-02,  1.0525e-02,  4.7492e-01,  ...,  1.8979e-01,
                         -9.4802e-02, -2.9527e-01],
                        [ 4.0963e-03,  3.1803e-01,  7.6918e-01,  ...,  1.5745e-02,
                         -4.1784e-01, -2.8113e-01]],

                       [[ 8.1112e-02, -2.4592e-01, -2.3660e-01,  ...,  5.1008e-02,
                          1.8750e-01,  2.4982e-01],
                        [-7.3754e-02, -3.0185e-01, -2.3367e-01,  ...,  1.0958e-01,
                          1.1808e-01,  5.0307e-02],
                        [-7.4244e-02, -2.4595e-01, -1.4838e-01,  ...,  1.9751e-01,
                          1.3078e-01,  1.3623e-01],
                        ...,
                        [-1.1046e-01, -6.7051e-02,  5.3822e-02,  ...,  2.9773e-01,
                          1.9333e-01,  1.7446e-02],
                        [-1.0371e-01, -9.8284e-02,  6.3600e-02,  ...,  3.0716e-01,
                          2.1886e-01, -4.1964e-03],
                        [-7.7000e-02,  7.6450e-02,  3.3828e-01,  ...,  4.4999e-01,
                          3.3961e-02,  1.2452e-02]]],


                      [[[ 2.2809e-02,  4.2991e-02,  2.1433e-02,  ...,  2.9756e-03,
                          4.1628e-03, -1.8607e-02],
                        [ 8.8062e-02,  9.9434e-02,  1.3185e-02,  ..., -2.4065e-02,
                          1.8570e-03, -1.8438e-03],
                        [ 1.2189e-01,  1.2206e-01,  1.0606e-02,  ..., -4.8498e-02,
                         -6.3361e-02, -7.2829e-03],
                        ...,
                        [ 2.3690e-01,  3.2949e-01,  1.4413e-01,  ..., -1.9832e-01,
                         -1.9657e-01,  3.3161e-02],
                        [ 1.9778e-01,  2.1857e-01,  1.0197e-01,  ..., -2.5074e-01,
                         -1.6853e-01,  1.6127e-02],
                        [ 1.2385e-01,  7.6209e-02,  2.4674e-02,  ..., -2.6733e-01,
                         -2.0076e-01,  2.9784e-04]],

                       [[ 1.1462e-01,  1.3557e-01,  2.8108e-02,  ..., -4.1830e-02,
                          6.8617e-03,  2.5310e-02],
                        [ 2.4844e-01,  2.8807e-01,  8.8655e-02,  ..., -8.6585e-02,
                         -6.1327e-02,  1.6255e-02],
                        [ 2.9706e-01,  3.7345e-01,  8.4224e-02,  ..., -2.5476e-01,
                         -2.4606e-01, -4.8291e-02],
                        ...,
                        [ 5.3112e-01,  6.8208e-01,  2.5231e-01,  ..., -5.9058e-01,
                         -4.8042e-01, -1.3168e-02],
                        [ 4.6590e-01,  5.6589e-01,  1.6813e-01,  ..., -6.4654e-01,
                         -4.5533e-01,  6.7977e-03],
                        [ 3.3126e-01,  2.8732e-01,  2.6376e-02,  ..., -5.9879e-01,
                         -4.0429e-01,  7.0927e-03]],

                       [[ 8.6603e-02,  9.8494e-02, -3.2440e-02,  ..., -4.8989e-02,
                          3.9894e-03, -4.5399e-03],
                        [ 1.7799e-01,  1.8441e-01,  3.5420e-02,  ..., -5.3928e-02,
                         -1.1518e-02,  1.3930e-02],
                        [ 1.5336e-01,  1.9236e-01,  5.3467e-03,  ..., -1.5720e-01,
                         -1.2461e-01, -2.8971e-02],
                        ...,
                        [ 3.1419e-01,  4.0312e-01,  1.4744e-01,  ..., -3.5207e-01,
                         -3.1404e-01,  1.7712e-02],
                        [ 2.5532e-01,  3.1150e-01,  1.5187e-01,  ..., -3.9310e-01,
                         -2.9233e-01,  2.3334e-02],
                        [ 2.0026e-01,  1.7301e-01,  6.0174e-02,  ..., -3.3814e-01,
                         -2.6533e-01, -5.3772e-03]]],


                      [[[ 4.3514e-02,  4.2754e-04, -8.3002e-02,  ...,  1.7350e-03,
                          4.2035e-03,  7.8877e-03],
                        [-9.7739e-02, -8.3412e-02, -1.1042e-01,  ..., -6.2833e-02,
                         -3.5562e-02, -3.1659e-02],
                        [ 1.7686e-02,  5.5336e-02,  3.1030e-02,  ...,  8.6115e-02,
                          7.6238e-02,  4.8345e-02],
                        ...,
                        [ 1.8837e-01,  2.5799e-01,  2.6883e-01,  ...,  1.2393e-01,
                          7.2508e-02,  3.0110e-02],
                        [-1.6221e-01, -2.2489e-01, -3.6862e-01,  ..., -2.0264e-01,
                         -9.7356e-02, -6.9690e-02],
                        [-2.2091e-01, -2.9295e-01, -2.9990e-01,  ..., -6.1255e-02,
                         -4.8997e-02, -2.4186e-02]],

                       [[ 2.0111e-02, -2.6092e-02, -9.4135e-02,  ...,  2.7096e-02,
                          3.2783e-02,  3.0859e-02],
                        [-9.8037e-02, -9.8726e-02, -1.2791e-01,  ..., -6.3321e-02,
                         -6.1073e-03, -1.6413e-02],
                        [ 6.8413e-02,  1.4157e-01,  1.3396e-01,  ...,  1.6313e-01,
                          8.9346e-02,  6.6405e-02],
                        ...,
                        [ 2.6107e-01,  3.4826e-01,  3.3640e-01,  ...,  1.7630e-01,
                          8.0338e-02,  2.4264e-02],
                        [-2.5785e-01, -3.3455e-01, -5.0598e-01,  ..., -3.3177e-01,
                         -2.3652e-01, -1.5328e-01],
                        [-3.0157e-01, -4.6701e-01, -5.5214e-01,  ..., -2.2254e-01,
                         -1.7677e-01, -1.2696e-01]],

                       [[ 1.1053e-02, -1.1701e-04, -3.4482e-02,  ...,  8.0569e-02,
                          2.9517e-02,  2.5344e-02],
                        [-3.2420e-02, -1.2325e-02, -3.3980e-02,  ..., -4.9384e-02,
                         -3.9851e-02, -1.2306e-02],
                        [ 2.4051e-02,  2.2650e-02,  7.7699e-03,  ...,  3.5604e-02,
                          4.1747e-03,  1.5310e-02],
                        ...,
                        [ 7.5493e-02,  1.0189e-01,  1.2886e-01,  ...,  9.8020e-02,
                          5.6341e-02,  8.5829e-02],
                        [-1.1549e-01, -1.3862e-01, -1.9950e-01,  ..., -1.1208e-01,
                         -6.3442e-02, -1.5216e-02],
                        [-1.1036e-01, -1.7584e-01, -2.0169e-01,  ..., -4.5618e-02,
                         -6.1155e-02, -1.0701e-02]]]], device='cuda:0')),
             ('backbone.bn1.weight',
              tensor([ 1.0302,  1.4978,  1.8853,  1.1581,  2.5466,  1.2864,  1.1616,  1.0618,
                       1.9414,  1.6254,  1.2452,  0.4556,  1.4022,  1.3309,  1.3997,  1.3033,
                       1.4642,  1.5272,  1.0179,  1.3549,  1.5156,  1.3647,  0.8484,  1.0714,
                       0.6859,  0.7332,  1.0270,  0.9272,  2.6814,  1.3328,  1.8360,  1.7825,
                       1.5928,  1.3807,  0.7373,  1.0661,  1.5666,  0.9782,  0.8400, -0.0367,
                       1.0426,  2.7808,  0.9540,  2.6764,  1.0563,  1.0860,  1.4125,  0.0072,
                       0.8140,  1.8427,  1.6823,  1.5420,  0.0121,  0.9427,  1.2981,  1.0469,
                       2.0245,  0.6376,  1.7078,  1.4693,  0.0121,  1.7865,  1.3963,  1.3737],
                     device='cuda:0')),
             ('backbone.bn1.bias',
              tensor([ 0.5433,  3.2087,  3.1882,  2.4482, -3.4323,  2.6226,  2.2123,  0.5607,
                       4.4466,  1.1396,  0.5353, -1.6506,  2.0675,  1.0119,  2.6098,  0.3434,
                       2.7922,  1.2808,  1.6557,  2.6934,  2.9983,  0.8722,  0.5646,  2.0137,
                       1.4980,  2.3073,  0.6513,  0.5922, -5.2873, -0.0392,  4.1049,  0.4350,
                       0.3720,  0.0410,  1.6422,  0.2435,  0.6106,  0.6771,  1.9258, -0.3218,
                       0.5050, -2.9827,  0.6633, -4.6968,  0.1066,  0.5296,  2.2068, -0.0977,
                       0.4194,  2.5756,  2.9928,  0.9225, -0.1730,  1.1005,  2.3045,  0.9203,
                       2.9438,  0.3173,  2.0329,  1.0708, -0.1642,  3.8934,  0.4067,  0.2151],
                     device='cuda:0')),
             ('backbone.bn1.running_mean',
              tensor([-7.3343e-02, -8.1278e-01,  2.2671e+00, -2.3880e-01, -1.2460e+00,
                      -1.5516e-01,  1.2826e-01,  1.5419e-02, -4.7395e+00, -3.8836e-02,
                      -5.0694e-02,  5.6052e-45,  2.6896e-01,  3.2252e-03, -3.1175e-01,
                       2.4225e-02, -4.1377e-01,  4.9927e+00,  3.6408e-01, -3.1933e-01,
                       7.1608e-01,  1.4239e-02, -1.9269e-02,  4.7238e-02,  4.4278e-02,
                      -1.2412e+00,  5.8049e-02, -9.7069e-02,  4.3083e+00,  7.9756e-01,
                      -1.3462e+00,  1.1252e-01,  2.7085e-02, -5.0033e-03,  4.6831e-01,
                      -3.3745e-02, -2.2967e+00, -7.1730e-02, -9.5229e-02, -5.6052e-45,
                      -8.7141e-02, -2.8278e+00,  2.9397e-02,  1.3701e+00, -4.1542e-03,
                      -1.4505e-01,  3.4658e-01,  5.6052e-45,  2.6253e-02,  1.3073e+00,
                      -1.0923e+00, -6.4840e-02,  5.6052e-45, -1.1625e-01, -2.6742e-01,
                      -1.0088e-01,  2.1942e+00, -1.8120e-02, -4.6662e+00, -1.3420e-02,
                      -5.6052e-45,  1.7722e+00, -3.9734e-02, -2.4327e-03], device='cuda:0')),
             ('backbone.bn1.running_var',
              tensor([5.8038e+00, 2.9798e+01, 1.5989e+02, 1.4062e+00, 1.6142e+02, 2.0027e+00,
                      1.4697e-01, 3.7530e+00, 4.8269e+02, 1.8593e+00, 2.5488e+00, 5.6052e-45,
                      4.7999e+00, 1.7146e+00, 7.2040e+00, 1.0680e+01, 6.9112e+00, 3.0076e+01,
                      9.8494e+00, 1.0227e+01, 3.6460e+01, 3.1048e+00, 2.6046e+00, 2.1714e+00,
                      7.7331e-01, 3.4254e+00, 3.4456e+00, 2.9431e+01, 8.7449e+01, 3.0596e+01,
                      7.1892e+01, 6.1134e+01, 2.6721e+01, 2.7348e+01, 1.5124e+00, 4.3958e+00,
                      2.6203e+01, 6.0762e+00, 1.9982e+00, 5.6052e-45, 3.3576e+00, 3.8401e+01,
                      3.4449e+00, 1.6436e+02, 5.5805e+00, 2.0997e+01, 9.1118e+00, 5.6052e-45,
                      2.0347e+00, 1.1360e+02, 1.0323e+02, 9.4140e+00, 5.6052e-45, 8.0756e+00,
                      5.2475e+00, 9.4497e+00, 2.0540e+01, 1.4199e+00, 2.5573e+01, 2.0054e+00,
                      5.6052e-45, 1.0330e+02, 5.9365e+01, 2.2843e+01], device='cuda:0')),
             ('backbone.bn1.num_batches_tracked',
              tensor(375288, device='cuda:0')),
             ('backbone.layer1.0.conv1.weight',
              tensor([[[[-2.5069e-01, -1.9098e-01,  1.2852e-01],
                        [-3.5716e-01, -1.3567e-01,  5.6451e-02],
                        [-3.7388e-01, -1.9269e-01,  1.2258e-01]],

                       [[ 4.2903e-02,  3.3840e-02,  2.1274e-01],
                        [-2.3263e-01, -3.0090e-01, -5.8093e-02],
                        [-2.2002e-01, -2.1043e-01,  1.3852e-01]],

                       [[-2.0081e-01, -1.2221e-01,  1.4454e-01],
                        [-7.6078e-01, -8.1728e-01, -4.5632e-01],
                        [-2.0636e-01, -1.9969e-01,  1.6046e-01]],

                       ...,

                       [[ 2.7173e-02,  7.3437e-02,  1.6718e-01],